openapi: 3.0.0
info:
  title: TimeWise API
  description: API для управления пользователями, задачами и событиями в приложении TimeWise.
  version: 1.0.0

servers:
  - url: http://localhost:4000

paths:
  /api/signup:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                birthdate:
                  type: string
                  format: date
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
                  nullable: true
                country:
                  type: string
                  nullable: true
                city:
                  type: string
                  nullable: true
                phone:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Успешная регистрация
        '400':
          description: Ошибка валидации данных

  /api/login:
    post:
      summary: Вход пользователя в систему
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверные учетные данные

  /api/tasks:
    post:
      summary: Создание новой задачи
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                due_date:
                  type: string
                  format: date
      responses:
        '201':
          description: Задача успешно создана
        '401':
          description: Необходима авторизация

    get:
      summary: Получение всех задач
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    due_date:
                      type: string
                      format: date
        '401':
          description: Необходима авторизация

  /api/tasks/{id}:
    get:
      summary: Получение задачи по ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Информация о задаче
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  due_date:
                    type: string
                    format: date
        '404':
          description: Задача не найдена
        '401':
          description: Необходима авторизация

    put:
      summary: Обновление задачи
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                due_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Задача успешно обновлена
        '404':
          description: Задача не найдена
        '401':
          description: Необходима авторизация

    delete:
      summary: Удаление задачи
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Задача успешно удалена
        '404':
          description: Задача не найдена
        '401':
          description: Необходима авторизация

  /api/events:
    post:
      summary: Создание нового события
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                date:
                  type: string
                  format: date
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Событие успешно создано
        '401':
          description: Необходима авторизация

    get:
      summary: Получение всех событий
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список событий
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    date:
                      type: string
                      format: date
                    description:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
        '401':
          description: Необходима авторизация

  /api/events/{id}:
    get:
      summary: Получение события по ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Информация о событии
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  date:
                    type: string
                    format: date
                  description:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
        '404':
          description: Событие не найдено
        '401':
          description: Необходима авторизация

    put:
      summary: Обновление события
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                date:
                  type: string
                  format: date
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Событие успешно обновлено
        '404':
          description: Событие не найдено
        '401':
          description: Необходима авторизация

    delete:
      summary: Удаление события
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Событие успешно удалено
        '404':
          description: Событие не найдено
        '401':
          description: Необходима авторизация

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
